//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autentification
    {
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Роль { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
