//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Альбомы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Альбомы()
        {
            this.Песни = new HashSet<Песни>();
        }
    
        public int Номер_альбома { get; set; }
        public string Название_альбома { get; set; }
        public string Жанр { get; set; }
        public Nullable<System.TimeSpan> Общая_длина { get; set; }
        public Nullable<int> Кол_во_песен { get; set; }
        public string Язык { get; set; }
        public Nullable<bool> EP { get; set; }
        public string Паспортные_данные_исполнителя { get; set; }
    
        public virtual Исполнитель Исполнитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Песни> Песни { get; set; }
    }
}
