//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выполнение_услуги
    {
        public int Номер_услуги { get; set; }
        public int Срок_выполнения { get; set; }
        public int Номер_песни { get; set; }
        public string Номер_договора { get; set; }
        public string Код_услуги { get; set; }
        public decimal Стоимость { get; set; }
    
        public virtual Договоры Договоры { get; set; }
        public virtual Перечень_услуг Перечень_услуг { get; set; }
        public virtual Песни Песни { get; set; }
    }
}
