//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public string Код_услуги { get; set; }
        public Nullable<int> Перезаписи { get; set; }
        public Nullable<int> Фрагменты { get; set; }
        public string Что_записывается { get; set; }
        public Nullable<int> Сопр_инструменты { get; set; }
        public int Битрейт { get; set; }
    
        public virtual Перечень_услуг Перечень_услуг { get; set; }
    }
}
