//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исполнитель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Исполнитель()
        {
            this.Альбомы = new HashSet<Альбомы>();
            this.Договоры = new HashSet<Договоры>();
        }
    
        public string Паспорт_Исполнителя { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Кол_во_альбомов { get; set; }
        public Nullable<System.DateTime> Карьера { get; set; }
        public Nullable<int> Кол_во_наград { get; set; }
        public string Страна { get; set; }
        public string Эл_почта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Альбомы> Альбомы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договоры> Договоры { get; set; }
    }
}
