//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Перечень_услуг
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Перечень_услуг()
        {
            this.Выполнение_услуги = new HashSet<Выполнение_услуги>();
        }
    
        public string Код_услуги { get; set; }
        public string Оборудование { get; set; }
        public string Название { get; set; }
        public string Паспорт_сотрудника { get; set; }
    
        public virtual Аранжировка Аранжировка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выполнение_услуги> Выполнение_услуги { get; set; }
        public virtual Запись Запись { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Сведение Сведение { get; set; }
    }
}
