//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Песни
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Песни()
        {
            this.Выполнение_услуги = new HashSet<Выполнение_услуги>();
        }
    
        public int Номер_песни { get; set; }
        public string Название_песни { get; set; }
        public int Битрейт { get; set; }
        public System.TimeSpan Длина { get; set; }
        public int Номер_альбома { get; set; }
        public Nullable<int> Сопр_инструменты { get; set; }
    
        public virtual Альбомы Альбомы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выполнение_услуги> Выполнение_услуги { get; set; }
    }
}
