//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Перечень_услуг = new HashSet<Перечень_услуг>();
        }
    
        public string Паспорт_сотрудника { get; set; }
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Телефон { get; set; }
        public string Пол { get; set; }
        public decimal Зарплата { get; set; }
        public string Номер_труд_книги { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Перечень_услуг> Перечень_услуг { get; set; }
        public virtual Autentification Autentification { get; set; }
    }
}
